name: Update Hafzan Composite Index

on:
  schedule:
    - cron: '0 1 * * *'  # Every day at 1 AM UTC
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Generate updated index.html
        run: |
          python generate_chart.py

      - name: Commit and push changes to gh-pages
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "GitHub Actions Bot"
          git checkout -b gh-pages
          git add index.html
          git commit -m "Daily update"
          git push origin gh-pages --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
